### ISSUE TITLE
Service Port List in RPC must have 2 elements

### ISSUE THREAD

**Issue by carloperocchio** [rvilalta/ietf-te-path-computation#16]
Questions and answers discussion: Italo Busi, Sergio Belotti, Daniele Ceccarelli, Francesco Lazzeri, Gianmarco Bruno, Carlo Perocchio
Monday, December 05, 2016

Q:       in ‘statelessComputeP2PPath’ service port is a list of 2 elements, where each of them has a source and a destination: why? 

Context: PC-API

R:
       input {
         list servicePort {
           min-elements 2;
           max-elements 2;
           uses PathCompServicePort;
           description "List of service ports.";
         }
Switch to 1 ??? The list might be useful for the bulk path computation. Like the SVEC used in PCEP (or a simplified version). With the plain list the same constraints must be applied to all entries, while with the SVEC it is possible to apply different constraints to different end points.

**Case1**: Many tunnel independent from each other (e.g. for global reoptimization or simultaneous path computation for a bulk of tunnels), with different end points

**Case2**: different paths form the same tunnel and hence same end point, e.g. working and protection path

**Case3**: different ingress and egress points (for multi domain) but the same characteristics. E.g. choice of the right ASBRs to pass from a domain to another.

**Comment by italobusi** [comment]
Italo/Sergio/Ricard:

@rvilalta : Update as follow:

`list servicePort { min-elements 1; uses PathCompServicePort; description "List of service ports."; }
`

**Comment by italobusi** [comment]
I have prepared one slide to describe use case 3 and how the change would allow reducing the number of RPC requests:

[bulk-path-computation-case3.pptx](https://github.com/rvilalta/ietf-te-path-computation/files/720091/bulk-path-computation-case3.pptx)

@carloperocchio : is this figure correctly representing the issue?

**Comment by carloperocchio** [comment]
Yes, it is because you have performed also the pruning of path computation towards ASBR on the same side (back to previous domain) as MDSC should do: the rpc request is not a generic any to any.

**Comment by italobusi** [comment]
This comment is pending resolution of issue #14

**Comment by italobusi** [comment]
The service port is now defined as:

```
       |  +---- servicePort*
       |  |  +---- source?          inet:ip-address
       |  |  +---- destination?     inet:ip-address
       |  |  +---- src-tp-id?       binary
       |  |  +---- dst-tp-id?       binary
       |  |  +---- bidirectional
       |  |     +---- association
       |  |        +---- id?              uint16
       |  |        +---- source?          inet:ip-address
       |  |        +---- global-source?   inet:ip-address
       |  |        +---- type?            identityref
       |  |        +---- provisioing?     identityref

```

I am not sure this new definition would help addressing the issue shown in the slide, expecially in case of tunnel segments

**Comment by sergiobelotti** [comment]
The service port is now defined as:

       |  +---- servicePort*
       |  |  +---- source?          inet:ip-address
       |  |  +---- destination?     inet:ip-address
       |  |  +---- src-tp-id?       binary
       |  |  +---- dst-tp-id?       binary
       |  |  +---- bidirectional
       |  |     +---- association
       |  |        +---- id?              uint16
       |  |        +---- source?          inet:ip-address
       |  |        +---- global-source?   inet:ip-address
       |  |        +---- type?            identityref
       |  |        +---- provisioing?     identityref

1) We agreed to add explicit-route-objects container, to align with te-tunnel model when setting up tunnel segment. e.g. domain B in the attached picture. 
[bulk-path-computation-case-04.pptx](https://github.com/rvilalta/ietf-te-path-computation/files/1663758/bulk-path-computation-case-04.pptx), 

There are concerns on the usage of explicit-route-object container just to indicate the related tunnel segment end points. 
@efralaz to raise the concern to the te-tunnel model authors/contributors 

It was noted also that it is not clear what happens when different explicit-route-objects are specified in the named-path-constraints and in the named-explicit-paths containers. 
What is the behavior in this case ?
@carloperocchio  

2) To move the bidirectional information  form Service Port to the request-list object . 
It is not clear which information is needed to qualify the bidirectional path options 

@italobusi @sergiobelotti
 
Carlo, Francesco, Italo and Sergio

**Comment by italobusi** [comment]
Pending discussion with TE Tunnel model authors of:
- https://github.com/ietf-mpls-yang/te/issues/22
- https://github.com/ietf-mpls-yang/te/issues/23
- bidirectional path options

@italobusi: raise the issue about bidirectional path options after IETF 101 cut-off

**Comment by italobusi** [comment]
In the latest draft update it has been clarified that, in the context of a typical multi-domain TE network, there could multiple choices for the ingress/egress points of a domain. In order to select the best pair of ingress/egress point, path computation needs to be requested between all the ingress/egress pairs.

The YANG model has been updated accordingly.

Open issue https://github.com/ietf-mpls-yang/te/issues/23 has been closed.

Open issue https://github.com/ietf-mpls-yang/te/issues/22 is out of scope for this issue: a new open issue #42 has been created instead.

Open issue on bidirectional path is also out of scope of this issue: a new open issue #43 has been created instead.
