### ISSUE TITLE
Metrics combination

### ISSUE THREAD

**Issue by carloperocchio** [rvilalta/ietf-te-path-computation#20]
Questions and answers discussion: Italo Busi, Sergio Belotti, Daniele Ceccarelli, Francesco Lazzeri, Gianmarco Bruno, Carlo Perocchio
Monday, December 05, 2016

Q: Looks like not possible to combine different metrics (single metric-type field).

Context: PC-API

**Comment by italobusi** [comment]
Italo/Sergio/Ricard:

Only one metric-type is possible in the TE module:

```
      leaf metric-type {
        type identityref {
          base path-metric-type;
        }
        default path-metric-te;
        description
          "The tunnel path metric type.";
      }

```

**Comment by ietf-mpls-yang** [comment]
just to be clear, are you asking to optimize for 2 (e.g. additive metrics?).. This is not commonly done in path computation since it is NP hard. However, if you meant optimizing for 1 while adding limit on the other, that should be possible.

**Comment by sergiobelotti** [comment]
the request is for one metric and put boundary values for others (1 or more). Where can be deduced that this option is already possible ?

**Comment by efralaz** [comment]
I believe that, unless there are strong reasons to do in a different way, the interface for path computation should be aligned with the features of the PCEP protocol, which is conceived for the same purpose.
According to RFC 5440 a Path Computation request can include an arbitrary number of METRIC objects.
A metric object specifies the following information:
- Type of metric (a number of different metrics have been defined in RFC5440 and in other IETF documents, including IGP metric, TE metric, number of Hops, Latency, Latency variation, Packet loss and more usable for single or bulk LSP path computation: see also RFC5541 and draft-ietf-pce-pcep-service-aware)
- Whether the metric has to be reported or not in the reply
- Whether the metric is an objective metric or a bound
- If the metric is a bound, the value of the bound itself.
PCEP is quite liberal with the rules to mix multiple metrics. The only rule is that it's not possible to have two bounds or two objective metrics of the same type.
It's allowed to have two different objective metrics, and is also allowed to have multiple bounds of different types, and any mix of these. 
How PCE will solve the problem is outside the scope of the document, as usual. 
I believe that also this model should allow whatever is not inconsistent in an evident way. 
Even though some combination of constraints are well known to lead to NP-Hard algorithms, why we should prevent someone to provide, for example, sub-optimal solutions with euristics that solve the problem in a scalable way ? If instead PCE cannot support a particular combination of constraint, it could well answer an error telling that it's unsupported.

**Comment by sergiobelotti** [comment]
We can consider closed after new Optimization-metric in tunnel model
grouping optimizations_config {
    description "Optimization metrics configuration grouping";
    leaf metric-type {
      type identityref {
        base te-types:path-metric-type;
      }
      description "TE path metric type";
    }
    leaf weight {
      type uint8;
      description "TE path metric normalization weight";
    }
  }

**Comment by carloperocchio** [comment]
rpc to be updated

**Comment by italobusi** [comment]
I think the issue has been closed

@carloperocchio : could you please check?
