### ISSUE TITLE
Missing setup priority and holding priority 

### ISSUE THREAD

**Issue by carloperocchio** [rvilalta/ietf-te-path-computation#23]
Questions and answers discussion: Italo Busi, Sergio Belotti, Daniele Ceccarelli, Francesco Lazzeri, Gianmarco Bruno, Carlo Perocchio
Monday, December 05, 2016

Q:  Setup priority and holding priority are missing

Context: TE tunnel: open issue

**Comment by italobusi** [comment]
Question for clarification: are these attributes impacting Path Computation or just need to be signaled when the path is setup in the network?

**Comment by efralaz** [comment]
They impact path computation, as PCE should use the bandwidth available on the links at the priority specified in the setup priority field. Holding priority must be also known to PCE in order to allow or not the preemption of the LSP, as per RFC5440: 
"  Setup Prio (Setup Priority - 8 bits):  The priority of the TE LSP
      with respect to taking resources, in the range of 0 to 7.  The
      value 0 is the highest priority.  The Setup Priority is used in
      deciding whether this session can preempt another session.

   Holding Prio (Holding Priority - 8 bits):  The priority of the TE LSP
      with respect to holding resources, in the range of 0 to 7.  The
      value 0 is the highest priority.  Holding Priority is used in
      deciding whether this session can be preempted by another session."

**Comment by sergiobelotti** [comment]
Looking at the draft-ietf-teas-yang-te-05 it issems the holding and setup priuority are already present. 

 leaf lsp-priority-hold {
      type uint8 {
        range "0..7";
      }
      description
        "TE LSP hold priority";
    }
    leaf lsp-protection-type {
      type identityref {
        base te-types:lsp-prot-type;
      }
      description "LSP protection type.";
    }

grouping tunnel-params_config

**Comment by sergiobelotti** [comment]
We need to discuss whether path-computation RPC should use all parameters included in tunnel-params_config or only a subset . 
@carloperocchio : please add "needs discussion" label to this issue.

**Comment by ietf-mpls-yang** [comment]
Ideally, we'll resuse the grouping or RPC can point to an existing "named-constraint set" that contains the constraints in advance. Let's discuss further.

**Comment by italobusi** [comment]
We are thinking to use the tunnel-params_config grouping but there are some parameters that seems not needed for a Path Computation RPC.

For example:
- identifier
- description
- admin-status
- hierarchical-link-id

Is there a way to use this group without getting this parameters?

**Comment by italobusi** [comment]
The value of setup priority influences the result of path computation while the value of the holding priority does not influence path computation.
Therefore the holding priority is needed for Tunnel setup but not needed for path computation. The value of setup priority instead is needed for both Tunnel setup and path computation,

Therefore also the holding priority in the tunnel-params_config grouping does not need to be reused in Path Computation RPC.

**Comment by italobusi** [comment]
In the -06 version of the TE-Tunnel model the following attributes have been added:

```
       |  |     |  +--rw setup-priority?           uint8
       |  |     |  +--rw hold-priority?            uint8

```

@carloperocchio : can we update the YANG file accordingly and close this open issue?

**Comment by carloperocchio** [comment]
As agreed with Italo, reopened to wait for path computation rpc definition update.

**Comment by italobusi** [comment]
The attributes needed to resolve this open issue are already defined in the te-tunnel model  within the tunnel-params_config grouping.

I think there are thee items to discuss before closing this open issue:

1) Is it possible to re-use only a sub-set of the attributes defined in tunnel-params_config grouping?

2) Which attributes in the tunnel-params_config grouping should not be used in path computation?

For example:
- identifier
- description
- admin-status
- hierarchical-link-id

3) Does the value of holding priority influence the path computation?

**Comment by italobusi** [comment]
**Offline discussion with Italo/Sergio/Ricard**

It is not possible to re-use only a sub-set of the attributes defined in the tunnel-params_config grouping.

We need to split it into two groupings.

Pending resolution of open issue #31

**Comment by italobusi** [comment]
We need to resolve the question whether holding priority influence path computation (and therefore should be specified in the RPC) or not

@efralaz : could you provide some thoughts?

**Comment by efralaz** [comment]
Setup priority and holding priority both affect path computation, but in different ways. They are used to manage LSP preemption: an LSP being signaled with a setup priority higher (that is with a lower value) than the holding priority of another LSP can preempt that LSP. Therefore setup priority of the LSP being computed must be used during path computation in order to know the level of priority of that LSP: that level must be compared against the holding priority of the LSPs already routed and present in the network (or, better, against the available bandwidth information which is usually available in TE topology as arrays “per-priority”: these arrays are computed taking into account the holding priority of the routed LSPs).
Therefore, the holding priority of the LSP being computed is not used during path computation, but will be used eventually when the LSP shall be actually activated.
In my view it’s not bad to provide also holding priority in the path computation request (as PCEP does), as this information can be stored in the TE-tunnel datastore and reused at tunnel activation time with no need to send it eventually. In case of stateless path computation this is of course not possible as no TE-tunnel info is created, but anyway the holding priority information is small and having the same format for the requests is a plus.

BR
Francesco

**Comment by italobusi** [comment]
The setup-priority and hold-priority are now part of the common-constraints_config container which is used by the Path Computation RPC.

I think the issue can be closed.

@carloperocchio : could you please check?
