### ISSUE TITLE
Review terminology in section 2

### ISSUE THREAD

**Issue by italobusi** [rvilalta/ietf-te-path-computation#58]
Micheal's comment: terminology in Section 2 a bit inconsistent

Review the terminology and check that it is consistent in the document

Check also the terminology used in section 3.2

**Comment by sergiobelotti** [comment]
We have addressed the terminology isseu in the attached word version. In the section 2 , we have a little different terminology about the controllers due to the fact does not exist a reference terminology that can be adapted to any use cases. For the rest of the document we think to have aligned the terminology.
Please have a look at this file :
[draft-ietf-teas-yang-path-computation-11@2020-10-23.docx](https://github.com/rvilalta/ietf-te-path-computation/files/5430722/draft-ietf-teas-yang-path-computation-11%402020-10-23.docx)

**Comment by michael-scharf** [comment]
This is a pretty old comment. I briefly scanned through the current document and terminology apparently has improved. Maybe this issue can be just closed.

**Comment by italobusi** [comment]
Closed with https://tools.ietf.org/html/draft-ietf-teas-yang-path-computation-11
